### ISSUE TITLE
HTTPError when running

### ISSUE THREAD

**Issue by jlehrer1** [seanbreckenridge/list_gh_contributions#2]
Put my personal access token in `token.txt`, got this error. 

```
~/Documents/Projects/statdepth/docs(master*) » list_gh_contributions --github-token ./token.txt 
Traceback (most recent call last):
  File "/Users/julian/opt/miniconda3/bin/list_gh_contributions", line 8, in <module>
    sys.exit(main())
  File "/Users/julian/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/julian/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/julian/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/julian/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/julian/opt/miniconda3/lib/python3.7/site-packages/list_gh_contributions/__main__.py", line 30, in main
    client = construct_client(github_token=gh_token)
  File "/Users/julian/opt/miniconda3/lib/python3.7/site-packages/list_gh_contributions/client.py", line 20, in construct_client
    client = Client(transport=transport, fetch_schema_from_transport=True)
  File "/Users/julian/opt/miniconda3/lib/python3.7/site-packages/gql/client.py", line 37, in __init__
    introspection = transport.execute(parse(introspection_query)).data
  File "/Users/julian/opt/miniconda3/lib/python3.7/site-packages/gql/transport/requests.py", line 124, in execute
    response.raise_for_status()
  File "/Users/julian/opt/miniconda3/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/graphql

```

**Comment by purarue** [comment]
seems to have been fixed by https://github.com/seanbreckenridge/list_gh_contributions/commit/67ab1bf45f1e81e3216e903ceee6002d3f0a495a
